name: do

on: [push]
env:
  weUrl: ''
  cowUrl: ''


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: download
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg curl zip -y
          git remote set-url origin https://${{ github.actor }}:${{ secrets.MY_ }}@github.com/${{ github.repository }}
          git pull --rebase
          curl -LJO https://github.com/ytdl-org/youtube-dl/releases/latest/download/youtube-dl
          chmod +x ./youtube-dl
          ./youtube-dl --config-location dl.conf
          zip -s 1984m downloaded.zip downloads/*.mp4
          cat play.list >> body.md
      - name: Upload firmware to WeTransfer
        continue-on-error: true
        run: |
          curl -sL https://git.io/file-transfer | bash -s beta
          wetrans=$(./transfer -p 16 --no-progress ./downloaded.zip)
          wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
          echo "WETRANS=$wetrans" >> $GITHUB_ENV
          echo "Download Link: ${{ env.EMOJI }} $wetrans ${{ env.EMOJI }} 🚀"     
