name: do

on: [push]
env:
  weUrl: ''
  cowUrl: ''


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: download
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg curl zip -y
          git remote set-url origin https://${{ github.actor }}:${{ secrets.MY_ }}@github.com/${{ github.repository }}
          git pull --rebase
          curl -LJO https://github.com/ytdl-org/youtube-dl/releases/latest/download/youtube-dl
          chmod +x ./youtube-dl
          ./youtube-dl --config-location dl.conf
          zip -s 1984m downloaded.zip downloads/*.mp4
          cat play.list >> body.md
      - name: Upload firmware to CowTransfer
        id: cowtransfer
        uses: tvrcgo/cowtransfer-action@master
        with:
          files: ./downloaded.*